/**
*  app ble_uuids.h
*/
#ifndef __BLE_UUIDS_H__
#define __BLE_UUIDS_H__

/**
 *  The SIT UUID was generated by the uuidgen utility, which gave
 *      6ba1de6b-3ab6-4d77-9ea1-cb642272ba01
 *  The last two hex digits (0xba, 0x01) were set to 0x00,0x00.
 *      6ba1de6b-3ab6-4d77-9ea1-cb6422720000
 *  This string was reversed to form a byte array to conform to 
 *  Zephyr's BLE API specifications.
 *      0000722264cb-a19e-774d-3ab6-6bdea16b
 *
 *  SIT UUID Base (common part) are the last 14 bytes of UUID.
 *  The first two bytes will be Service or Characteristic unique values.
 *  This is similar to the UUID16-type UUIDs specified by the BT SIG.
 */
#define SIT_UUID_BASE 0x01,0xba,0x72,0x22,0x64,0xcb,0xa1,0x9e,0x77,0x4d,0x3a,0xb6

#define SIT_UUID_SERVICE            0x00,0x00,0x00,0x00
#define SIT_UUID_NOTIFY             0x01,0x00,0x00,0x00
#define SIT_UUID_INT_COMMAND        0x02,0x00,0x00,0x00
#define SIT_UUID_JSON_COMMAND       0x03,0x00,0x00,0x00

/**
 *  SIT Service UUID: 6ba1de6b-3ab6-4d77-9ea1-cb6422720000
 */
#define BT_UUID_SIT_SERVICE_VAL \
	BT_UUID_128_ENCODE(0x6ba1de6b, 0x3ab6, 0x4d77, 0x9ea1, 0xcb6422720000)

#define BT_UUID_SIT_SERVICE \
    BT_UUID_DECLARE_128(BT_UUID_SIT_SERVICE_VAL)


/**
 *  SIT Characteristics UUIDs: 6ba1de6b-3ab6-4d77-9ea1-cb642272xxxx
 */
#define BT_UUID_SIT_POS_NOTIFY_VAL \
	BT_UUID_128_ENCODE(0x6ba1de6b, 0x3ab6, 0x4d77, 0x9ea1, 0xcb6422720001)
#define BT_UUID_SIT_POS_NOTIFY   \
    BT_UUID_DECLARE_128(BT_UUID_SIT_POS_NOTIFY_VAL)

#define BT_UUID_SIT_INT_COMMAND_VAL \
	BT_UUID_128_ENCODE(0x6ba1de6b, 0x3ab6, 0x4d77, 0x9ea1, 0xcb6422720002)
#define BT_UUID_SIT_INT_COMMAND   \
    BT_UUID_DECLARE_128(BT_UUID_SIT_INT_COMMAND_VAL)

#define BT_UUID_SIT_JSON_COMMAND_VAL \
	BT_UUID_128_ENCODE(0x6ba1de6b, 0x3ab6, 0x4d77, 0x9ea1, 0xcb6422720003)
#define BT_UUID_SIT_JSON_COMMAND   \
    BT_UUID_DECLARE_128(BT_UUID_SIT_JSON_COMMAND_VAL)


#endif  // __BLE_UUIDS_H__